# .github/workflows/main.yml

name: Daily Google Drive Backup

on:
  # Allows you to click “Run workflow” in the Actions UI immediately
  workflow_dispatch:
  # And also runs at midnight UTC every day
  schedule:
    - cron: '0 18 * * *' 

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Check out your repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip & install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r web-portal-automator-src/requirements.txt

      - name: Run Drive backup
        # run from inside your src folder so main.py sees credentials.json
        working-directory: web-portal-automator-src
        env:
          SOURCE_FOLDER_ID: '1-sVtj8AdMB7pQAadjB9_CUmQ67gOXswi'
          DEST_FOLDER_ID:   '10lXwcwYGsbdIYLhkL9862RP4Xi1L-p9v'
        run: |
          python main.py
