name: Daily Google Drive Backup

on:
  # lets you trigger it manually in the Actions UI
  workflow_dispatch:
  schedule:
    # runs every day at 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        # run pip install in the folder where requirements.txt lives
        working-directory: web-portal-automator-src
        run: |
          pip install -r requirements.txt

      - name: Run Drive backup
        # also run your script from that folder
        working-directory: web-portal-automator-src
        env:
          SOURCE_FOLDER_ID: '1-sVtj8AdMB7pQAadjB9_CUmQ67gOXswi'
          DEST_FOLDER_ID:   '10lXwcwYGsbdIYLhkL9862RP4Xi1L-p9v'
        run: |
          python main.py
